---
- hosts: all
  become: true
  user: ubuntu
  become_method: sudo
  tasks:
    - name: Install apache httpd  (state=present is optional)
      ansible.builtin.apt:
      name: apache2
      state: present
